/**
 * Fractional index: parity with the server, and the ordering properties.
 *
 * docs/08-testing.md asks that "the optimistic fractional index equals the server's".
 * The strongest form of that is a shared vector file: `ordering-vectors.json` is
 * generated by running the *Python* implementation
 * (`apps/api/src/coach/services/ordering.py`) and is replayed here against the
 * TypeScript port. If the two ever drift, this fails and names the input.
 *
 * Regenerate with the snippet in `scripts/dev.sh gen-ordering-vectors`.
 */

import { describe, expect, it } from 'vitest';

import {
  FIRST_KEY,
  keyBetween,
  nKeysBetween,
  orderForMove,
  OrderKeyError,
  validateKey,
} from '@/lib/ordering';
import vectors from '@/lib/ordering-vectors.json';

describe('parity with the Python implementation', () => {
  it.each(vectors.keyBetween)('keyBetween($a, $b) === $expected', ({ a, b, expected }) => {
    expect(keyBetween(a, b)).toBe(expected);
  });

  it.each(vectors.nKeysBetween)(
    'nKeysBetween($a, $b, $n) matches the server',
    ({ a, b, n, expected }) => {
      expect(nKeysBetween(a, b, n)).toEqual(expected);
    },
  );

  it.each(vectors.rebalance)('rebalance($n) matches the server', ({ n, expected }) => {
    expect(nKeysBetween(null, null, n)).toEqual(expected);
  });

  it('reproduces a 30-step insert sequence exactly', () => {
    const board: string[] = [];
    for (const step of vectors.sequence) {
      const previous = step.at > 0 ? board[step.at - 1]! : null;
      const following = step.at < board.length ? board[step.at]! : null;
      const key = keyBetween(previous, following);
      expect(key).toBe(step.key);
      board.splice(step.at, 0, key);
      expect(board).toEqual(step.board);
    }
  });
});

describe('ordering properties', () => {
  it('hands out the first key on an empty board', () => {
    expect(keyBetween(null, null)).toBe(FIRST_KEY);
  });

  it('keeps keys strictly increasing across inserts and moves', () => {
    let keys: string[] = [];
    // Deterministic pseudo-random walk: a repeatable stand-in for the hypothesis
    // property test on the Python side.
    let seed = 42;
    const next = (bound: number) => {
      seed = (seed * 1103515245 + 12345) % 2147483648;
      return seed % (bound + 1);
    };
    for (let step = 0; step < 200; step += 1) {
      if (keys.length < 2 || next(1) === 0) {
        const at = next(keys.length);
        const previous = at > 0 ? keys[at - 1]! : null;
        const following = at < keys.length ? keys[at]! : null;
        keys = [...keys.slice(0, at), keyBetween(previous, following), ...keys.slice(at)];
      } else {
        const from = next(keys.length - 1);
        const to = next(keys.length - 1);
        const rest = [...keys.slice(0, from), ...keys.slice(from + 1)];
        const previous = to > 0 ? rest[to - 1]! : null;
        const following = to < rest.length ? rest[to]! : null;
        keys = [...rest.slice(0, to), keyBetween(previous, following), ...rest.slice(to)];
      }
      expect([...keys].sort()).toEqual(keys);
      expect(new Set(keys).size).toBe(keys.length);
      keys.forEach(validateKey);
    }
  });

  it('does not grow the key under repeated appends', () => {
    let key = keyBetween(null, null);
    for (let i = 0; i < 500; i += 1) key = keyBetween(key, null);
    expect(key.length).toBeLessThanOrEqual(4);
  });

  it.each([
    ['a1', 'a1'],
    ['a2', 'a1'],
    ['b0', 'a0'],
  ])('refuses an out-of-sequence pair (%s, %s)', (a, b) => {
    expect(() => keyBetween(a, b)).toThrow(OrderKeyError);
  });

  it.each(['', '0', 'a', 'a0000000000', '!', 'a10'])('refuses the malformed key %s', (key) => {
    expect(() => validateKey(key)).toThrow(OrderKeyError);
  });
});

describe('orderForMove', () => {
  const board = [
    { id: 'a', order: 'a0' },
    { id: 'b', order: 'a1' },
    { id: 'c', order: 'a2' },
  ];

  it('moving to the top sorts before everything else', () => {
    const order = orderForMove(board, 'c', 0);
    expect(order < 'a0').toBe(true);
  });

  it('moving to the bottom sorts after everything else', () => {
    const order = orderForMove(board, 'a', 2);
    expect(order > 'a2').toBe(true);
  });

  it('moving into the middle lands strictly between the neighbours', () => {
    const order = orderForMove(board, 'a', 1);
    expect(order > 'a1').toBe(true);
    expect(order < 'a2').toBe(true);
  });

  it('computes the key the server would compute for the same neighbours', () => {
    // The client positions relative to the list *without* the moving row, which is the
    // same convention `plan_move` uses on the server.
    expect(orderForMove(board, 'c', 1)).toBe(keyBetween('a0', 'a1'));
  });

  it('clamps an out-of-range target rather than throwing', () => {
    expect(() => orderForMove(board, 'a', 99)).not.toThrow();
    expect(() => orderForMove(board, 'a', -5)).not.toThrow();
  });
});
